export const NOTIFICATION_ID = "NOTIFICATION_ID";
export const ALARM_ID = "ALARM_ID";

export const CREATE_ALARM = "CREATE_ALARM";
export const MODIFY_ALARM_TIME = "MODIFY_ALARM_TIME";
export const MODIFY_ALARM_REPEAT = "MODIFY_ALARM_REPEAT";
export const MODIFY_ALARM_VIBRATE = "MODIFY_ALARM_VIBRATE";
export const MODIFY_ALARM_ACTIVE = "MODIFY_ALARM_ACTIVE";
export const MODIFY_ALARM_DAYS = "MODIFY_ALARM_DAYS";
export const DELETE_ALARM = "DELETE_ALARM";

export const CONFIGURE_NOTIFICATION = "CONFIGURE_NOTIFICATION";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const MODIFY_NOTIFICATION = "MODIFY_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const SHOW_TIME_PICKER = "SHOW_TIME_PICKER";
export const SHOW_TIME_PICKER_WITH_TIME = "SHOW_TIME_PICKER_WITH_TIME";
export const ON_TIME_PICKED = "ON_TIME_PICKED";
export const HIDE_TIME_PICKER = "HIDE_TIME_PICKER";
