export const CREATE_ALARM = "CREATE_ALARM";
export const MODIFY_ALARM_REPEAT = "MODIFY_ALARM_REPEAT";
export const MODIFY_ALARM_VIBRATE = "MODIFY_ALARM_VIBRATE";
export const MODIFY_ALARM_ACTIVE = "MODIFY_ALARM_ACTIVE";
export const MODIFY_ALARM_DAYS = "MODIFY_ALARM_DAYS";
export const DELETE_ALARM = "DELETE_ALARM";
